# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy to gh-pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install sphinx
      run: |
        pip install sphinx
    - name: Build sphinx docs
      run: |
        cd docs
        make html
    - name: push to gh-pages
      run: |
        cd ..
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898281+github-actions[bot]@users.noreply.github.com"

        git add --all
        git add docs/build/
        git commit -m "get sphinx build"
        git push origin gh-pages
